### ISSUE TITLE
Missing Schema.js instructions

### ISSUE THREAD

**Issue by felixjchen** [mongodb-university/realm-tutorial-node-js#2]
Hi, I've completed https://docs.mongodb.com/realm/tutorial/nodejs-cli but I'm getting the following error:

```
 ❗
Error: Failed to read ObjectSchema: name must be of type 'string', got (undefined)
 ❗
```

Isn't this because schema.js is empty? There isn't any schema instructions in the tutorial

**Comment by cbush** [comment]
Sorry about that. It seems we introduced a regression in the documentation at some point. This has been fixed. Thanks for bringing it to our attention!
